### ISSUE TITLE
Cache usage

### ISSUE THREAD

**Issue by paulahy** [wultra/ssl-pinning-ios#24]
Hello, how are you?

In the scenario where the fingerprint data returned from the server is changed to invalid data, the component is using the cache and showing the transaction as valid.

I tried to use .update(mode: .forced), but even so, the data used in the certificate validation is the cache data.

`certStore?.update(mode: .forced, completion: { result, error in
            print("Result update: \(result) | \(String(describing: error))")
        })`

How to stop using cache data?

Thank you very much!

**Comment by paulahy** [comment]
Hello @petrdvorak,

so the biggest question is where does the component store the certificate cache?
Because even deleting the app from the device, the cache is kept. Why does this occur?

Thank you very much!

**Comment by petrdvorak** [comment]
Hello @paulahy, without more information about what you are trying do, we cannot help much. The information you provide is inconsistent with how the library should (and does in our projects) behave. Depending on what you did, we most likely keep the cache in the standard iOS Keychain. But this is not important, since we don't know if:

- You used PowerAuth integration - is it the case.
  - If so, what keychain configuration did you used.
- What code you are calling in a more general context (larger code snippet).
- What you mean by "invalid data".

If this helps, please schedule a call with me at: https://calendly.com/wultra/e-meeting, we will have a look...
